name: 'Update packages README.md'

on:
  push:
    paths:
      - '**/packages/**/*.spec'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          token: "${{ env.GITHUB_TOKEN }}"

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v31

      - name: 'Update README.md in packages directory'
        shell: bash
        run: |
          command='source ./scripts/setup-python-env.sh && ./scripts/generate-pkg-list-readme'
          echo '> nix develop --command bash -c "$command"'
          nix develop --command bash -c "$command"

      - name: 'Commit changes'
        shell: bash
        run: |
          echo "> USERNAME='github-actions[bot]'"
          USERNAME='github-actions[bot]'
          echo "> EMAIL='41898282+github-actions[bot]@users.noreply.github.com'"
          EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          echo '> git config --local user.name $USERNAME'
          git config --local user.name $USERNAME
          echo '> git config --local user.email $EMAIL'
          git config --local user.email $EMAIL
          echo '> git add -u'
          git add -u
          # Get the list of staged files
          STAGED_FILES=$(git diff --cached --name-only)

          if [ -n "$STAGED_FILES" ]; then
            echo "> commit_message=''"
            commit_message=''

            # Check if only flake.lock was updated
            if [ "$STAGED_FILES" == 'flake.lock' ]; then
              echo "> commit_message='bot: Updated \`flake.lock\`'"
              commit_message='bot: Updated `flake.lock`'
            else
              echo "> CURRENT_TIME=\$(date +'%Y-%m-%d %H:%M:%S')"
              CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
              echo '> commit_message="bot: Updated packages at $CURRENT_TIME UTC"'
              commit_message="bot: Updated packages at $CURRENT_TIME UTC"
            fi

            echo '> git commit -m "$commit_message"'
            git commit -m "$commit_message"
          fi

      - name: 'Push changes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: "${{ env.GITHUB_TOKEN }}"
          branch: "${{ github.ref }}"
